jitterbunk/bunk/urls.py
from django.urls import path

from . import views

app_name = "bunk"

urlpatterns = [
    path("bunkfeed/", views.main_bunk_feed),
    path("<int:id>/bunkfeed/", views.personal_bunk_feed, name="personal_feed"),
    path("bunkfeed/submit_bunk", views.submit_bunk, name="submit_bunk"),
    path("users/", views.user_list, name="user_list"),
    path("create_user/", views.create_user, name="create_user")
]

jitterbunk/jitterbunk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bunk/', include('bunk.urls'))
]

jitterbunk/bunk/models.py
from django.utils import timezone
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=200)
    photo = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

class Bunk(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    pub_date = models.DateTimeField('date published',default=timezone.now)

jitterbunk/bunk/views.py
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from django.db.models import Q
from django.forms.models import model_to_dict
from django.http import HttpResponse, HttpResponseRedirect


from .models import Bunk, User

# Create your views here.
    
def main_bunk_feed(request):
    bunks = Bunk.objects.all().order_by('-pub_date')
    
    return render(request, 'bunk/main_feed.html', {
        'bunks': bunks
    })
    
def personal_bunk_feed(request, id):
    user = User.objects.get(id=id)

    bunk_list = list(Bunk.objects.filter((Q(pub_date__lte=timezone.now())), (Q(from_user_id=id) | Q(to_user_id=id))).order_by('-pub_date'))

    incoming_bunk_list = [bunk for bunk in bunk_list if bunk.to_user == user]
    
    outgoing_bunk_list = [bunk for bunk in bunk_list if bunk.from_user == user]
    
    allusers = User.objects.exclude(id=id)

    print(len(allusers))
    return render(request, 'bunk/personal_feed.html', {
        'user': user,
        'incoming_bunk_list': incoming_bunk_list,
        'outgoing_bunk_list': outgoing_bunk_list,
        'allusers': allusers,
    })

def user_list(request):
    print("Hello World!")
    users = User.objects.all().order_by('-pub_date')
    return render(request, 'bunk/users.html', {
        'users': users
    })

def submit_bunk(request):
    from_id = request.POST['from_user']
    to_id = request.POST['to_user']
    
    print(from_id, to_id)

    new_bunk = Bunk.objects.create(from_user=User.objects.get(id=from_id), to_user=User.objects.get(id=to_id))

    new_bunk.save()

    return HttpResponseRedirect(f'/bunk/{from_id}/bunkfeed')

def create_user(request):
    username = request.POST['username']
    photo = request.POST['photo']

    user = User.objects.create(username=username, photo=photo)
    user.save()

    return HttpResponseRedirect(f'/bunk/users')

jitterbunk/bunk/templates/bunk/main_feed.html
<html>
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bunk/style.css' %}" />
  </head>
  <body>
    <h1 class="dash_name">The Bunkbox  📫</h1>
    <div class="personal_feed_page">
      <div class="bunk_boxes">
          <h2 class="box_title">All Bunks</h2>
        <div class="bunk_inbox">
          {% if bunks %} {% for bunk in bunks %}
          <div class="bunk_list_item">
            <div class="bunk_message">
                {{bunk.from_user.username}} bunked {{bunk.to_user.username}}!
              </div>
            <div class="bunk_date">🗓️: {{bunk.pub_date}}</div>
          </div>
          {% endfor %} {% else %}
          <div class="no_bunks">There are no bunks in the inbox.</div>
          {% endif %}
        </div>
      </div>
      <div class="bunk_outbox">
        <h2 class="box_title" id="send_bunk">Send a Bunk 📤</h2>
        <form
          class="bunk_form"
          action="{% url 'bunk:submit_bunk' %}"
          method="post"
        >
          {% csrf_token %}
          <label for="recipient">Who would you like to bunk?</label>
          <select id="recipient" name="to_user" class="to_select">
            <option disabled value="0">Cannot bunk from The Bunkbox</option>
          </select>
          <input type="hidden" value="{{user.id}}" name="from_user" />
          <button type="submit" disabled class="bunk_submit">Submit</button>
        </form>
      </div>
    </div>
  </body>
</html>

jitterbunk/bunk/templates/bunk/personal_feed.html
<html>
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bunk/style.css' %}" />
  </head>
  <body>
    <h1 class="dash_name">{{user.username}}'s Bunkbox 📫</h1>
    <div class="personal_feed_page">
      <div class="bunk_boxes">
        <h2 class="box_title">Inbox</h2>
        <div class="bunk_inbox">
          {% if incoming_bunk_list %} {% for bunk in incoming_bunk_list %}
          <div class="bunk_list_item">
            <div class="bunk_message">
              {{bunk.from_user.username}} bunked you!
            </div>
            <div class="bunk_date">🗓️: {{bunk.pub_date}}</div>
          </div>
          {% endfor %} {% else %}
          <div class="no_bunks">There are no bunks in the inbox.</div>
          {% endif %}
        </div>
        <h2 class="box_title">Outbox</h2>
        <div class="bunk_outbox">
          {% if outgoing_bunk_list %} {% for bunk in outgoing_bunk_list %}
          <div class="bunk_list_item">
            <div class="bunk_message">
              You bunked {{bunk.to_user.username}}!
            </div>
            <div class="bunk_date">🗓️: {{bunk.pub_date}}</div>
          </div>

          {% endfor %} {% else %}
          <div class="no_bunks">There are no bunks in the outbox.</div>
          {% endif %}
        </div>
      </div>
      <div class="bunk_outbox">
        <h2 class="box_title" id="send_bunk">Send a Bunk 📤</h2>
        <form
          class="bunk_form"
          action="{% url 'bunk:submit_bunk' %}"
          method="post"
        >
          {% csrf_token %}
          <label for="recipient">Who would you like to bunk?</label>
          <select id="recipient" name="to_user" class="to_select">
            {% for usr in allusers %}
            <option value="{{usr.id}}">{{usr.username}}</option>
            {% endfor %}
          </select>
          <input type="hidden" value="{{user.id}}" name="from_user" />
          <button type="submit" class="bunk_submit">Submit</button>
        </form>
      </div>
    </div>
  </body>
</html>

jitterbunk/bunk/templates/bunk/users.html
<html>
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bunk/style.css' %}" />
  </head>
  <body>
    <h1 class="dash_name">Bunkbox Users 📇</h1>
    {% if users %}
    <ul>
      {% for user in users %}
      <a href="{% url 'bunk:personal_feed' user.id %}">
        <li class="user_list_element">{{user.username}}</li>
      </a>
      {% endfor %}
    </ul>
    {% else %}
    <p>No users.</p>
    {% endif %}

    <h3 class="box_title">Create a New User</h3>

    <form class="bunk_form bunk_inbox" action="{% url 'bunk:create_user' %}" method="post">
      {% csrf_token %}
      <input type="textfield" id="username" name="username" class="to_select" placeholder="Username">
      <input type="textfield" id="photo" name="photo" class="to_select" placeholder="Password">
      <button type="submit" class="bunk_submit">Submit</button>
    </form>
  </body>
</html>